import {
  createRootRoute,
  createRoute,
  createRouter,
  type RouterHistory,
  Outlet,
  redirect,
} from "@tanstack/react-router"
import { AppShell } from "../components/AppShell"
import { ForbiddenView, NotFoundView } from "./system-views"
import { LoginView } from "./LoginView"
import { SetupView } from "./SetupView"
import { LiveView } from "./LiveView"
import { PlaybackView } from "./PlaybackView"
import { TimelineView } from "./TimelineView"
import { CamerasView } from "./CamerasView"
import { SchedulesView } from "./SchedulesView"
import { EventsView } from "./EventsView"
import { AlertsView } from "./AlertsView"
import { StorageView } from "./StorageView"
import { FilesView } from "./FilesView"
import { SystemView } from "./SystemView"
import { UsersView } from "./UsersView"
import { AuditView } from "./AuditView"
import { findNavItem, navigation } from "../lib/navigation"
import { useAuthStore } from "../stores/auth"

const flat = navigation.flatMap((g) => g.items)

/** First module the signed-in user is actually allowed to open. */
function landingKey(): string {
  const { atLeast } = useAuthStore.getState()
  const first = flat.find((i) => atLeast(i.requires))
  return first?.key ?? "forbidden"
}

const rootRoute = createRootRoute({
  component: () => <Outlet />,
  notFoundComponent: NotFoundView,
})

/* ------------------------------------------------------------- public */

const loginRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/login",
  component: LoginView,
  beforeLoad: () => {
    const { status } = useAuthStore.getState()
    // Sending an authenticated user back to /login would look like a broken
    // session; send them where they were actually headed instead.
    if (status === "authenticated") throw redirect({ to: "/" })
    if (status === "needs-setup") throw redirect({ to: "/setup" })
  },
})

const setupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/setup",
  component: SetupView,
  beforeLoad: () => {
    const { status } = useAuthStore.getState()
    if (status === "authenticated") throw redirect({ to: "/" })
    if (status === "anonymous") throw redirect({ to: "/login" })
  },
})

/* ------------------------------------------------------------ guarded */

const shellRoute = createRoute({
  getParentRoute: () => rootRoute,
  id: "shell",
  component: () => <AppShell />,
  beforeLoad: ({ location }) => {
    const { status } = useAuthStore.getState()
    if (status === "bootstrapping") return
    if (status === "needs-setup") throw redirect({ to: "/setup" })
    if (status !== "authenticated") {
      // Preserve the destination so a deep link survives the login detour.
      throw redirect({
        to: "/login",
        search: { redirect: location.href },
      })
    }
  },
})

/**
 * Routes are written out one by one rather than generated by a helper.
 *
 * That is deliberate: a `moduleRoute(key: string)` helper widens `path` to
 * `string`, and TanStack Router can only type `Link to={...}` from literal
 * paths, so the whole app would degrade to `string`. The cost of the
 * verbosity is that `router.tsx` now repeats each path from
 * `lib/navigation.ts`; `routes/router.spec.tsx` asserts the two agree so the
 * duplication cannot silently drift.
 */
function guard(key: string) {
  const item = findNavItem(key)
  if (!item) throw new Error(`unknown module: ${key}`)
  return () => {
    if (!useAuthStore.getState().atLeast(item.requires)) {
      throw redirect({ to: "/forbidden", search: { from: key } })
    }
  }
}

const liveRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/live",
  component: LiveView,
  beforeLoad: guard("live"),
})

const playbackRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/playback",
  component: PlaybackView,
  beforeLoad: guard("playback"),
})

const timelineRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/timeline",
  component: TimelineView,
  beforeLoad: guard("timeline"),
})

const camerasRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/cameras",
  component: CamerasView,
  beforeLoad: guard("cameras"),
})

const schedulesRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/recording-schedules",
  component: SchedulesView,
  beforeLoad: guard("schedules"),
})

const eventsRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/events",
  component: EventsView,
  beforeLoad: guard("events"),
})

const alertsRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/alerts",
  component: AlertsView,
  beforeLoad: guard("alerts"),
})

const storageRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/storage",
  component: StorageView,
  beforeLoad: guard("storage"),
})

const filesRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/files",
  component: FilesView,
  beforeLoad: guard("files"),
})

const systemRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/system",
  component: SystemView,
  beforeLoad: guard("system"),
})

const usersRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/users",
  component: UsersView,
  beforeLoad: guard("users"),
})

const auditRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/audit",
  component: AuditView,
  beforeLoad: guard("audit"),
})

const indexRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/",
  beforeLoad: () => {
    throw redirect({ to: `/${landingKey()}` as never })
  },
})

const forbiddenRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/forbidden",
  component: ForbiddenView,
})

export const routeTree = rootRoute.addChildren([
  loginRoute,
  setupRoute,
  shellRoute.addChildren([
    indexRoute,
    forbiddenRoute,
    liveRoute,
    playbackRoute,
    timelineRoute,
    camerasRoute,
    schedulesRoute,
    eventsRoute,
    alertsRoute,
    storageRoute,
    filesRoute,
    systemRoute,
    usersRoute,
    auditRoute,
  ]),
])

/**
 * Factory rather than a bare singleton: the router owns navigation state, so
 * a shared instance would leak the previous test's path into the next one.
 * `main.tsx` keeps the app-wide singleton; tests build their own.
 */
export function createAppRouter(
  history?: RouterHistory | undefined,
) {
  return createRouter({ routeTree, history, defaultNotFoundComponent: NotFoundView })
}

export const router = createAppRouter()

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router
  }
}

export type AppRouter = ReturnType<typeof createAppRouter>
