import {
  createRootRoute,
  createRoute,
  createRouter,
  type RouterHistory,
  Outlet,
  redirect,
} from "@tanstack/react-router"
import { AppShell } from "../components/AppShell"
import { ForbiddenView, NotFoundView } from "./system-views"
import { LoginView } from "./LoginView"
import { SetupView } from "./SetupView"
import { LiveView } from "./LiveView"
import { PlaybackView } from "./PlaybackView"
import { TimelineView } from "./TimelineView"
import { CamerasView } from "./CamerasView"
import { SchedulesView } from "./SchedulesView"
import { EventsView } from "./EventsView"
import { AlertsView } from "./AlertsView"
import { StorageView } from "./StorageView"
import { FilesView } from "./FilesView"
import { SystemView } from "./SystemView"
import { UsersView } from "./UsersView"
import { AuditView } from "./AuditView"
import { AccountPanel } from "../components/account/AccountPanel"
import { findNavItem, navigation } from "../lib/navigation"
import { useAuthStore } from "../stores/auth"

const flat = navigation.flatMap((g) => g.items)

/** First module the signed-in user is actually allowed to open. */
function landingKey(): string {
  const { atLeast } = useAuthStore.getState()
  const first = flat.find((i) => atLeast(i.requires))
  return first?.key ?? "forbidden"
}

const rootRoute = createRootRoute({
  component: () => <Outlet />,
  notFoundComponent: NotFoundView,
})

/* ------------------------------------------------------------- public */

const loginRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/login",
  component: LoginView,
  beforeLoad: () => {
    const { status } = useAuthStore.getState()
    // Sending an authenticated user back to /login would look like a broken
    // session; send them where they were actually headed instead.
    if (status === "authenticated") throw redirect({ to: "/" })
    if (status === "needs-setup") throw redirect({ to: "/setup" })
  },
})

const setupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/setup",
  component: SetupView,
  beforeLoad: () => {
    const { status } = useAuthStore.getState()
    if (status === "authenticated") throw redirect({ to: "/" })
    if (status === "anonymous") throw redirect({ to: "/login" })
  },
})

/* ------------------------------------------------------------ guarded */

const shellRoute = createRoute({
  getParentRoute: () => rootRoute,
  id: "shell",
  component: () => <AppShell />,
  beforeLoad: ({ location }) => {
    const { status } = useAuthStore.getState()
    if (status === "bootstrapping") return
    if (status === "needs-setup") throw redirect({ to: "/setup" })
    if (status !== "authenticated") {
      // Preserve the destination so a deep link survives the login detour.
      throw redirect({
        to: "/login",
        search: { redirect: location.href },
      })
    }
  },
})

/**
 * Routes are written out one by one rather than generated by a helper.
 *
 * That is deliberate: a `moduleRoute(key: string)` helper widens `path` to
 * `string`, and TanStack Router can only type `Link to={...}` from literal
 * paths, so the whole app would degrade to `string`. The cost of the
 * verbosity is that `router.tsx` now repeats each path from
 * `lib/navigation.ts`; `routes/router.spec.tsx` asserts the two agree so the
 * duplication cannot silently drift.
 */
function guard(key: string) {
  const item = findNavItem(key)
  if (!item) throw new Error(`unknown module: ${key}`)
  return () => {
    if (!useAuthStore.getState().atLeast(item.requires)) {
      throw redirect({ to: "/forbidden", search: { from: key } })
    }
  }
}

const liveRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/live",
  component: LiveView,
  beforeLoad: guard("live"),
})

/**
 * Deep-link parameters.
 *
 * Both are optional so the page behaves exactly as it did before them when it
 * is opened bare, which is still the common case. They exist so a "review this
 * moment" link from the file browser actually lands on that moment instead of
 * on whatever the camera happened to be showing — and, incidentally, so a
 * playback URL can be pasted to a colleague and mean the same thing.
 *
 * `at` stays a string on both sides of the parse. TanStack Router types what
 * you *write* into a link from the same declaration it types what you *read*,
 * so returning a parsed number here would make the outgoing link a number
 * while every producer of it — a segment's `start_at` — is a string. The page
 * parses it, and drops a value that does not parse.
 */
function playbackSearch(search: Record<string, unknown>) {
  return {
    camera: typeof search.camera === "string" ? search.camera : undefined,
    at: typeof search.at === "string" ? search.at : undefined,
  }
}

/**
 * Adapts the deep-link search params to the view's props.
 *
 * The parse lives here rather than in `playbackSearch` so that the param
 * keeps one type on both sides: TanStack types an outgoing `Link`'s search
 * from the same declaration it types an incoming read, so returning a parsed
 * number would make every producer of the link — a segment's `start_at`, a
 * string — a type error. A value that does not parse is dropped rather than
 * passed on as NaN, which downstream renders as an empty timeline and reads
 * as "there is no footage here".
 */
function PlaybackRouteComponent() {
  const { camera, at } = playbackRoute.useSearch()
  const atMs = at === undefined ? undefined : Date.parse(at)
  return (
    <PlaybackView
      initialCameraId={camera}
      initialAtMs={atMs === undefined || Number.isNaN(atMs) ? undefined : atMs}
    />
  )
}

const playbackRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/playback",
  component: PlaybackRouteComponent,
  validateSearch: playbackSearch,
  beforeLoad: guard("playback"),
})

const timelineRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/timeline",
  component: TimelineView,
  beforeLoad: guard("timeline"),
})

const camerasRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/cameras",
  component: CamerasView,
  beforeLoad: guard("cameras"),
})

const schedulesRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/recording-schedules",
  component: SchedulesView,
  beforeLoad: guard("schedules"),
})

const eventsRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/events",
  component: EventsView,
  beforeLoad: guard("events"),
})

const alertsRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/alerts",
  component: AlertsView,
  beforeLoad: guard("alerts"),
})

const storageRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/storage",
  component: StorageView,
  beforeLoad: guard("storage"),
})

const filesRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/files",
  component: FilesView,
  beforeLoad: guard("files"),
})

const systemRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/system",
  component: SystemView,
  beforeLoad: guard("system"),
})

const usersRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/users",
  component: UsersView,
  beforeLoad: guard("users"),
})

/**
 * The signed-in account's own page.
 *
 * **No `guard(...)`**, deliberately — `guard` resolves a navigation module and
 * a minimum role, and this page is the opposite of a privileged one: it is the
 * signed-in user's own sessions, password and API tokens. Every endpoint on it
 * is scoped to the caller's own account by the server, so an Operator and an
 * Administrator get the same page. A role check here would lock out exactly the
 * users who most need a way to change a leaked password.
 */
const accountRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/account",
  component: AccountPanel,
})

const auditRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/audit",
  component: AuditView,
  beforeLoad: guard("audit"),
})

const indexRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/",
  beforeLoad: () => {
    throw redirect({ to: `/${landingKey()}` as never })
  },
})

const forbiddenRoute = createRoute({
  getParentRoute: () => shellRoute,
  path: "/forbidden",
  component: ForbiddenView,
})

export const routeTree = rootRoute.addChildren([
  loginRoute,
  setupRoute,
  shellRoute.addChildren([
    indexRoute,
    forbiddenRoute,
    liveRoute,
    playbackRoute,
    timelineRoute,
    camerasRoute,
    schedulesRoute,
    eventsRoute,
    alertsRoute,
    storageRoute,
    filesRoute,
    systemRoute,
    usersRoute,
    accountRoute,
    auditRoute,
  ]),
])

/**
 * Factory rather than a bare singleton: the router owns navigation state, so
 * a shared instance would leak the previous test's path into the next one.
 * `main.tsx` keeps the app-wide singleton; tests build their own.
 */
export function createAppRouter(
  history?: RouterHistory | undefined,
) {
  return createRouter({ routeTree, history, defaultNotFoundComponent: NotFoundView })
}

export const router = createAppRouter()

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router
  }
}

export type AppRouter = ReturnType<typeof createAppRouter>
